services:

  hz:
    image: hazelcast/hazelcast-enterprise:5.4
    environment:
      JAVA_OPTS: -Dhazelcast.config=/project/hazelcast.yaml
      HZ_LICENSEKEY: ${HZ_LICENSEKEY}
    volumes:
      - ".:/project"
    networks:
      - hznet

  mc:
    image: hazelcast/management-center:5.4
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hz:5701
    ports:
      - "8080:8080"
    networks:
      - hznet

  refdata-loader:
    image: amazoncorretto:21
    command: >
      java -Dhazelcast.client.config=/project/hazelcast-client.yaml
        -jar /project/refdata-loader/target/refdata-loader-1.0-SNAPSHOT.jar
    environment:
      HZ_SERVERS: hz
      HZ_CLUSTER_NAME: dev
      CARD_COUNT: 10000
    volumes:
      - ".:/project"
    networks:
      - hznet

  authorization-service:
    image: amazoncorretto:21
    command: >
     java -Dhazelcast.client.config=/project/hazelcast-client.yaml
        -jar /project/authorization-service/target/authorization-service-1.0-SNAPSHOT.jar
    environment:
     HZCLIENT_INSTANCENAME: authorization_service
    volumes:
     - ".:/project"
    ports:
     - "8888:8080"
    networks:
     - hznet


networks:
  hznet: 
  
